### ISSUE TITLE
Starting up svelte app using this template not working for me

### ISSUE THREAD

**Issue by aldeka** [sveltejs/template-webpack#6]
I followed the instructions at https://svelte.technology/guide#getting-started for getting up and running with svelte. I installed degit for the first time, used this template, ran `npm install`. But when I run `npm run dev`, I get an error:

```
$ npm run dev

> svelte-app@1.0.0 dev /Users/karen/Code/lillekoi
> webpack-serve --content public --hot

/Users/karen/Code/lillekoi/node_modules/@webpack-contrib/config-loader/lib/load.js:78
      log.error(chalk`An error ocurred while trying to load {grey ${configPath}}
                     ^

TypeError: chalk is not a function
    at module.exports (/Users/karen/Code/lillekoi/node_modules/@webpack-contrib/config-loader/lib/load.js:78:22)
    at module.exports (/Users/karen/Code/lillekoi/node_modules/@webpack-contrib/config-loader/lib/index.js:13:15)
    at load (/Users/karen/Code/lillekoi/node_modules/webpack-serve/lib/config.js:105:12)
    at module.exports (/Users/karen/Code/lillekoi/node_modules/webpack-serve/lib/options.js:62:10)
    at module.exports (/Users/karen/Code/lillekoi/node_modules/webpack-serve/index.js:16:10)
    at Object.<anonymous> (/Users/karen/Code/lillekoi/node_modules/webpack-serve/cli.js:82:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 dev: `webpack-serve --content public --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-app@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/karen/.npm/_logs/2018-05-17T04_58_14_543Z-debug.log
```

I'm not sure what went wrong, what further information would be enlightening, or how to fix it. Is there an additional `webpack` dependency or something besides what this template's package.json provides, that might have gotten left out of the svelte docs? Fwiw, my NodeJS version is v8.11.2, the current listed LTS version.

**Comment by thewindsword** [comment]
I install chalk to solve it
`npm install chalk`

**Comment by fjanon** [comment]
Thanks, it helped.

I would suggest to remove that non essential dependency, or at least fix the instructions.

**Comment by antony** [comment]
This looks like a problem with the `@webpack-contrib` module, not this template. Having said that, I've just followed these instructions myself (using the current LTS) and there doesn't appear to be an issue.

Either way, the issue appears to be environment specific and there isn't anything we can fix here.
